name = "prod-j51b5"
main = "build/worker/shim.mjs"
compatibility_date = "2025-04-02"

[build]
command = "cargo install -q worker-build && worker-build --release"

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true

